# Done to increase the memory available to gradle.
	org.gradle.jvmargs=-Xmx2048M
	enabled_platforms=fabric,neoforge,forge

	loom.allowMismatchedPlatformVersion = true

# General Properties
	minecraft_version=1.17.1

# Mod Properties
	mod_version = 1.1.1+1.21.9
	maven_group = io.wispforest
	archives_base_name = lmft

# Fabric Dependencies
	fabric_loader_version=0.17.2

# NeoForge Dependencies
    # Minimum Version - 1.20.2
	neoforge_version=20.2.93

    # Minimum Version - Latest
    # neoforge_version=21.10.2-beta

# Forge Dep
    # Minimum Version - 1.17.1
    forge_version=37.1.1

    # Minimum Version - Latest
    # forge_version=37.1.1
