modLoader = "javafml"
loaderVersion = "[1,)"
#issueTrackerURL = ""
license = "CC0-1.0"

[[mods]]
modId = "lmft"
version = "${version}"
displayName = "Load My F***ing Tags"
authors = "Blodhgarm"
description = '''
Simple mod that makes Tag Loading less of a Pain
'''
logoFile = "assets/lmft/icon.png"
[[mixins]]
config = 'lmft-common.mixins.json'
[[mixins]]
config = 'lmft.mixins.json'

[[dependencies.lmft]]
modId = "neoforge"
required = true
versionRange = "[20,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.lmft]]
modId = "minecraft"
required = true
versionRange = "[1.20,)"
ordering = "NONE"
side = "BOTH"
